### ISSUE TITLE
Given implementation of rmdir segfaults if the parent directory is empty

### ISSUE THREAD

**Issue by gratejames** [CSCI210Mines/project2#1]
### Issue:
The template/solution implementation of rmdir segfaults if the parent directory (of the directory attempting to be removed) is empty, instead of printing `RMDIR ERROR: directory <DIRECTORY> does not exist` as expected.

### To reproduce:
1. Run `solution_executable/main`
2. Execute `rmdir a`
3. Program segfaults

### or

1. Run `solution_executable/main`
2. Execute `mkdir a`
3. Execute `rmdir a/b`
5. Program segfaults

I understand it isn't that relevant to the assignment, but I thought I'd let you know.

**Comment by tolgacan** [comment]
Thank you for finding out this error case! We will fix this bug in a day or two.

**Comment by tolgacan** [comment]
The bug should be fixed now with the latest update.
